-- MoneyPuck v2 side-by-side schema.
-- These tables intentionally do not replace the original NHL API schema.

CREATE TABLE IF NOT EXISTS mp_import_runs (
    import_id SERIAL PRIMARY KEY,
    source_root TEXT NOT NULL,
    imported_at TIMESTAMP DEFAULT NOW(),
    shots_rows INTEGER DEFAULT 0,
    team_game_rows INTEGER DEFAULT 0,
    skater_rows INTEGER DEFAULT 0,
    goalie_rows INTEGER DEFAULT 0,
    team_season_rows INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS mp_shots (
    season INTEGER NOT NULL,
    game_id INTEGER NOT NULL,
    shot_id INTEGER NOT NULL,
    home_team_code VARCHAR(8),
    away_team_code VARCHAR(8),
    is_playoff_game BOOLEAN,
    home_team_won BOOLEAN,
    period INTEGER,
    time_seconds INTEGER,
    event VARCHAR(16),
    shooting_team_code VARCHAR(8),
    defending_team_code VARCHAR(8),
    is_home_shot BOOLEAN,
    home_goals INTEGER,
    away_goals INTEGER,
    home_skaters INTEGER,
    away_skaters INTEGER,
    shooting_skaters INTEGER,
    defending_skaters INTEGER,
    strength_state VARCHAR(8),
    x_cord NUMERIC,
    y_cord NUMERIC,
    x_cord_adjusted NUMERIC,
    y_cord_adjusted NUMERIC,
    arena_adjusted_x_cord NUMERIC,
    arena_adjusted_y_cord NUMERIC,
    shot_angle NUMERIC,
    shot_angle_adjusted NUMERIC,
    shot_distance NUMERIC,
    shot_type VARCHAR(32),
    goal BOOLEAN,
    shot_was_on_goal BOOLEAN,
    shot_on_empty_net BOOLEAN,
    shot_rebound BOOLEAN,
    shot_generated_rebound BOOLEAN,
    shot_rush BOOLEAN,
    shot_goalie_froze BOOLEAN,
    shot_play_stopped BOOLEAN,
    shot_play_continued_in_zone BOOLEAN,
    shot_play_continued_outside_zone BOOLEAN,
    shot_angle_rebound_royal_road BOOLEAN,
    shot_angle_plus_rebound_speed NUMERIC,
    off_wing BOOLEAN,
    x_goal NUMERIC,
    x_froze NUMERIC,
    x_rebound NUMERIC,
    x_play_stopped NUMERIC,
    x_play_continued_in_zone NUMERIC,
    x_play_continued_outside_zone NUMERIC,
    x_shot_was_on_goal NUMERIC,
    time_since_last_event NUMERIC,
    time_until_next_event NUMERIC,
    time_since_faceoff NUMERIC,
    time_difference_since_change NUMERIC,
    shooter_player_id INTEGER,
    shooter_name TEXT,
    shooter_left_right VARCHAR(8),
    shooter_time_on_ice NUMERIC,
    shooter_time_on_ice_since_faceoff NUMERIC,
    goalie_id_for_shot INTEGER,
    goalie_name_for_shot TEXT,
    shooting_team_average_time_on_ice NUMERIC,
    shooting_team_max_time_on_ice NUMERIC,
    defending_team_average_time_on_ice NUMERIC,
    defending_team_max_time_on_ice NUMERIC,
    defending_team_average_time_on_ice_since_faceoff NUMERIC,
    defending_team_max_time_on_ice_since_faceoff NUMERIC,
    home_penalty1_time_left NUMERIC,
    home_penalty1_length NUMERIC,
    away_penalty1_time_left NUMERIC,
    away_penalty1_length NUMERIC,
    last_event_category VARCHAR(32),
    last_event_team VARCHAR(16),
    last_event_x_cord NUMERIC,
    last_event_y_cord NUMERIC,
    last_event_x_cord_adjusted NUMERIC,
    last_event_y_cord_adjusted NUMERIC,
    distance_from_last_event NUMERIC,
    speed_from_last_event NUMERIC,
    PRIMARY KEY (season, game_id, shot_id)
);

CREATE TABLE IF NOT EXISTS mp_team_games (
    season INTEGER NOT NULL,
    game_id INTEGER NOT NULL,
    game_date DATE,
    team VARCHAR(8) NOT NULL,
    opposing_team VARCHAR(8),
    home_or_away VARCHAR(8),
    situation VARCHAR(16) NOT NULL,
    playoff_game BOOLEAN,
    ice_time NUMERIC,
    x_goals_for NUMERIC,
    x_goals_against NUMERIC,
    flurry_adjusted_x_goals_for NUMERIC,
    flurry_adjusted_x_goals_against NUMERIC,
    shot_attempts_for NUMERIC,
    shot_attempts_against NUMERIC,
    unblocked_shot_attempts_for NUMERIC,
    unblocked_shot_attempts_against NUMERIC,
    shots_on_goal_for NUMERIC,
    shots_on_goal_against NUMERIC,
    goals_for NUMERIC,
    goals_against NUMERIC,
    low_danger_x_goals_for NUMERIC,
    medium_danger_x_goals_for NUMERIC,
    high_danger_x_goals_for NUMERIC,
    low_danger_x_goals_against NUMERIC,
    medium_danger_x_goals_against NUMERIC,
    high_danger_x_goals_against NUMERIC,
    rebounds_for NUMERIC,
    rebounds_against NUMERIC,
    rebound_x_goals_for NUMERIC,
    rebound_x_goals_against NUMERIC,
    penalties_for NUMERIC,
    penalties_against NUMERIC,
    faceoffs_won_for NUMERIC,
    faceoffs_won_against NUMERIC,
    PRIMARY KEY (season, game_id, team, situation)
);

CREATE TABLE IF NOT EXISTS mp_skaters_season (
    player_id INTEGER NOT NULL,
    season INTEGER NOT NULL,
    name TEXT,
    team VARCHAR(8) NOT NULL,
    position VARCHAR(8),
    situation VARCHAR(16) NOT NULL,
    games_played NUMERIC,
    ice_time NUMERIC,
    shifts NUMERIC,
    game_score NUMERIC,
    on_ice_x_goals_percentage NUMERIC,
    off_ice_x_goals_percentage NUMERIC,
    i_f_x_goals NUMERIC,
    i_f_flurry_adjusted_x_goals NUMERIC,
    i_f_shot_attempts NUMERIC,
    i_f_shots_on_goal NUMERIC,
    i_f_goals NUMERIC,
    i_f_rebounds NUMERIC,
    i_f_x_rebounds NUMERIC,
    i_f_faceoffs_won NUMERIC,
    faceoffs_won NUMERIC,
    faceoffs_lost NUMERIC,
    shots_blocked_by_player NUMERIC,
    penalties NUMERIC,
    penalties_drawn NUMERIC,
    on_ice_f_x_goals NUMERIC,
    on_ice_a_x_goals NUMERIC,
    on_ice_f_shot_attempts NUMERIC,
    on_ice_a_shot_attempts NUMERIC,
    on_ice_a_high_danger_x_goals NUMERIC,
    on_ice_a_medium_danger_x_goals NUMERIC,
    on_ice_a_low_danger_x_goals NUMERIC,
    off_ice_f_x_goals NUMERIC,
    off_ice_a_x_goals NUMERIC,
    x_goals_for_after_shifts NUMERIC,
    x_goals_against_after_shifts NUMERIC,
    PRIMARY KEY (player_id, season, team, situation)
);

CREATE TABLE IF NOT EXISTS mp_goalies_season (
    player_id INTEGER NOT NULL,
    season INTEGER NOT NULL,
    name TEXT,
    team VARCHAR(8) NOT NULL,
    position VARCHAR(8),
    situation VARCHAR(16) NOT NULL,
    games_played NUMERIC,
    ice_time NUMERIC,
    x_goals NUMERIC,
    goals NUMERIC,
    unblocked_shot_attempts NUMERIC,
    x_rebounds NUMERIC,
    rebounds NUMERIC,
    x_freeze NUMERIC,
    freezes NUMERIC,
    x_on_goal NUMERIC,
    on_goal NUMERIC,
    flurry_adjusted_x_goals NUMERIC,
    low_danger_x_goals NUMERIC,
    medium_danger_x_goals NUMERIC,
    high_danger_x_goals NUMERIC,
    low_danger_goals NUMERIC,
    medium_danger_goals NUMERIC,
    high_danger_goals NUMERIC,
    PRIMARY KEY (player_id, season, team, situation)
);

CREATE TABLE IF NOT EXISTS mp_teams_season (
    team VARCHAR(8) NOT NULL,
    season INTEGER NOT NULL,
    situation VARCHAR(16) NOT NULL,
    games_played NUMERIC,
    ice_time NUMERIC,
    x_goals_for NUMERIC,
    x_goals_against NUMERIC,
    flurry_adjusted_x_goals_for NUMERIC,
    flurry_adjusted_x_goals_against NUMERIC,
    shot_attempts_for NUMERIC,
    shot_attempts_against NUMERIC,
    goals_for NUMERIC,
    goals_against NUMERIC,
    high_danger_x_goals_for NUMERIC,
    high_danger_x_goals_against NUMERIC,
    rebound_x_goals_for NUMERIC,
    rebound_x_goals_against NUMERIC,
    PRIMARY KEY (team, season, situation)
);

CREATE INDEX IF NOT EXISTS idx_mp_shots_pk_against
    ON mp_shots (defending_team_code, season, game_id)
    WHERE shooting_skaters > defending_skaters AND defending_skaters IN (3, 4);

CREATE INDEX IF NOT EXISTS idx_mp_shots_goalie
    ON mp_shots (goalie_id_for_shot, season)
    WHERE goalie_id_for_shot IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_mp_shots_last_event
    ON mp_shots (last_event_category, season);

CREATE INDEX IF NOT EXISTS idx_mp_skaters_pk
    ON mp_skaters_season (situation, season, player_id);

CREATE INDEX IF NOT EXISTS idx_mp_team_games_pk
    ON mp_team_games (situation, season, team);
